- import_playbook: mariadb.yaml
- import_playbook: rabbitmq.yaml
- import_playbook: memcached.yaml

- import_playbook: keystone.yaml
  when:
    - '"keystone" in enabled_service'

- import_playbook: glance.yaml
  when:
    - '"glance" in enabled_service'

- import_playbook: placement.yaml
  when:
    - '"placement" in enabled_service'

- import_playbook: nova.yaml
  when:
    - '"nova" in enabled_service'

#- import_playbook: cinder.yaml

- import_playbook: horizon.yaml
  when:
    - '"horizon" in enabled_service'

- import_playbook: aodh.yaml
  when:
    - '"aodh" in enabled_service'

- import_playbook: gnocchi.yaml
  when:
    - '"gnocchi" in enabled_service'

- import_playbook: ceilometer.yaml
  when:
    - '"ceilometer" in enabled_service'

- import_playbook: rally.yaml
  when:
    - '"rally" in enabled_service'

- import_playbook: kolla.yaml
  when:
    - '"kolla" in enabled_service'

- import_playbook: tempest.yaml
  when:
    - '"tempest" in enabled_service'

- import_playbook: cyborg.yaml
  when:
    - '"cyborg" in enabled_service'

- import_playbook: heat.yaml
  when:
    - '"heat" in enabled_service'
