- import_playbook: mariadb.yaml
- import_playbook: rabbitmq.yaml
- import_playbook: memcached.yaml
- import_playbook: keystone.yaml
  when:
    - '"keystone" in enabled_service'
#- import_playbook: nova.yaml
#- import_playbook: cinder.yaml
- import_playbook: aodh.yaml
  when:
    - '"aodh" in enabled_service'
