- name: Config OpenStack yum repo
  hosts: all
  become: yes
  tasks:
    - name: Install openstack-releases package
      yum:
        name:
        - openstack-release-{{ openstack_release }}
      ignore_errors: yes
- name: Set hostname mappings
  hosts: all
  become: yes
  tasks:
    - name: Set hostname for hosts
      shell: |
        cat << EOF >> /etc/hosts
        {{ hostvars['controller']['ansible_default_ipv4']['address'] }} {{ hostvars['controller']['ansible_hostname'] }}
        {{ hostvars['compute01']['ansible_default_ipv4']['address'] }} {{ hostvars['compute01']['ansible_hostname'] }}
        {{ hostvars['compute02']['ansible_default_ipv4']['address'] }} {{ hostvars['compute02']['ansible_hostname'] }}
        EOF
      when: oos_env_type == 'cluster'
- name: Install Database
  hosts: all
  become: yes
  tasks:
    - name: Update python bin
      shell: |
        yum install -y python2 python3
        rm -f /usr/bin/python
        ln -s /usr/bin/python3 /usr/bin/python
      ignore_errors: yes
