- name: Config OpenStack yum repo
  hosts: all
  become: yes
  tasks:
    - name: Install openstack-releases package
      yum:
        name:
        - openstack-release-{{ openstack_release }}
      ignore_errors: yes
- name: Install Database
  hosts: all
  become: yes
  tasks:
    - name: Update python bin
      shell: |
        yum install -y python2 python3
        rm -f /usr/bin/python
        ln -s /usr/bin/python3 /usr/bin/python
      ignore_errors: yes
