- name: Install openstack-keystone
  hosts: controller
  become: yes
  tasks:
    - name: Install openstack-keystone
      yum:
        name:
          - mariadb
          - memcached
          - httpd
