- name: Create {{ database }} database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ database }}"
    state: present
    login_unix_socket: "/var/lib/mysql/mysql.sock"

- name: grant {{ database }} database user privilege(local)
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ database }}"
    password: "{{ mysql_project_password }}"
    host: localhost
    priv: "{{ user }}.*:ALL"
    state: present
    login_unix_socket: "/var/lib/mysql/mysql.sock"

- name: grant {{ database }} database user privilege(remote)
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ database }}"
    password: "{{ mysql_project_password }}"
    host: "%"
    priv: "{{ user }}.*:ALL"
    state: present
    login_unix_socket: "/var/lib/mysql/mysql.sock"
