- name: Create {{ project }} database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ project }}"
    state: present
    login_unix_socket: "/var/lib/mysql/mysql.sock"

- name: grant {{ project }} database user privilege(local)
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ project }}"
    password: "{{ mysql_project_password }}"
    host: localhost
    priv: "{{ project }}.*:ALL"
    state: present
    login_unix_socket: "/var/lib/mysql/mysql.sock"

- name: grant {{ project }} database user privilege(remote)
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ project }}"
    password: "{{ mysql_project_password }}"
    host: "%"
    priv: "{{ project }}.*:ALL"
    state: present
    login_unix_socket: "/var/lib/mysql/mysql.sock"
